
spring:
  application:
    name: dine-in-order-api  # Added a space after "name:"

  # DataSource configuration
  datasource:
    url: ${MYSQL_URL} # Added a space after "url:"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true  # Added a space after "show-sql:"
    hibernate:
      ddl-auto: update  # Added a space after "ddl-auto:"

app:
  base-url: /api/v1